
name: Sync Upstream

env:
  FRONTEND_REPO: "https://github.com/totrieuvy/SWP.git"
  BACKEND_REPO: "https://github.com/LearningCoding101/SWP_Jewelry.git"
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  BRANCH: "main"
  BRANCHFE: "master"

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Create CODING directory and clone FRONTEND
        run: |
          rm -rf CODING/FRONTEND
          mkdir -p CODING/FRONTEND
          git clone --branch ${{ env.BRANCHFE }} ${{ env.FRONTEND_REPO }} CODING/FRONTEND
      - name: Create CODING directory and clone BACKEND
        run: |
          rm -rf CODING/BACKEND
          mkdir -p CODING/BACKEND
          git clone --branch ${{ env.BRANCH }} ${{ env.BACKEND_REPO }} CODING/BACKEND

    
      - name: Remove .git directory from CODING/FRONTEND and CODING/BACKEND
        run: |
          rm -rf CODING/FRONTEND/.git
          rm -rf CODING/BACKEND/.git
      - name: Remove sensitive file if exists
        run: |
          rm -f CODING/BACKEND/src/main/resources/firebase-admin.json
          echo "CODING/BACKEND/src/main/resources/firebase-admin.json" >> CODING/BACKEND/.gitignore
      - name: Commit and Push changes
        run: |
          git config --global user.name "LearningCoding101"
          git config --global user.email "hahoang33322@gmail.com"
          git add .
      
          # Check if there are changes to commit
          git diff --quiet && git diff --cached --quiet || {
            git commit -m "Sync repositories and remove sensitive file"
            git push origin ${{ env.BRANCH }} --no-verify
          }
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
